name: Run Python SDK E2E Tests
  
on:
  pull_request:
    branches:
      - main
env:
  TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10"]  
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install -r requirements.txt
        working-directory: ./apps/python-sdk
      - name: Test with pytest  
        run: |  
          pytest firecrawl/__tests__/e2e_withAuth/test.py 
        working-directory: ./apps/python-sdk
